language: cpp

compiler: gcc

# Blacklist
branches:
  except:
    - gh-pages
    
# Environment variables
env:
  global:
    - GH_REPO_NAME: blatt-7-aufgabe-1-team
    - DOXYFILE: $TRAVIS_BUILD_DIR/DoxyfileAVLTreeConfig
    - GH_REPO_REF: https://github.com/ob-algdati-ws17/blatt-7-aufgabe-1-team

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      
script:
    - mkdir build
    - pwd
    - ls -lisa
    - cd build && cmake ..
    - make
    - make test
    
# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh